ConnectX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
from core.views import index,about
from userprofile.forms import LoginForm
urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('leads.urls')),
    path('dashboard/clients/', include('clients.urls')),
    path('dashboard/teams/', include('teams.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('search/', include('core.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name ='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .import views
app_name = 'search'
urlpatterns=[
path('', views.search, name='search'),]

leads/urls.py
from django.urls import path
from .import views
app_name='leads'
urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('add-lead/', views.LeadCreateView.as_view(), name='add'),
]

leads/models.py
from django.contrib.auth.models import User
from django.db import models
from teams.models import Team


class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )
    plot = 'plot'
    readyTomove = 'readyTomove'
    apartment = 'apartment'

    Property_type=(
        (plot, 'plot'),
        (readyTomove, 'readyTomove'),
        (apartment, 'apartment'),
    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=11,default=' ')
    Address = models.TextField(max_length=50, default=' ',blank=False,null=False)
    property_price = models.IntegerField(default='00')
    property_size = models.CharField(max_length=25,default=' ')
    property_locality = models.CharField(max_length=25, default=' ')
    property_type = models.CharField(max_length=11, choices=Property_type, default=plot)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

leads/forms.py
from django import forms
from .models import Lead


class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'phone', 'Address', 'property_price', 'property_size', 'property_locality', 'property_type', 'priority')

leads/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from clients.models import Client
from teams.models import Team
from .models import Lead
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class LeadListView(LoginRequiredMixin, ListView):
    model = Lead
    def get_queryset(self):
        queryset = super(LeadListView, self).get_queryset()
        team = self.request.user.userprofile.active_team
        return queryset.filter(team=team,converted_to_client=False)
                                        #created_by=self.request.user,

class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead

    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()
        team = self.request.user.userprofile.active_team
        return queryset.filter(team=team, pk=self.kwargs.get('pk'))


class LeadDeleteView(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')
    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()
        team = self.request.user.userprofile.active_team
        return queryset.filter(team=team, pk=self.kwargs.get('pk'))
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class LeadUpdateView(LoginRequiredMixin, UpdateView):
    model = Lead
    fields = ('name', 'email', 'phone', 'Address', 'property_price', 'property_size', 'property_locality', 'property_type', 'priority')
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit Lead'
        return context

    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()
        team = self.request.user.userprofile.active_team
        return queryset.filter(team=team, pk=self.kwargs.get('pk'))


class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    fields = ('name', 'email', 'phone', 'Address', 'property_price', 'property_size', 'property_locality', 'property_type', 'priority')
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team = self.request.user.userprofile.get_active_team()
        context['team'] = team
        context['title'] = 'Add Lead'
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = self.request.user.userprofile.get_active_team()
        self.object.save()
        return redirect(self.get_success_url())



class ConvertToClientView(View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
        team = self.request.user.userprofile.get_active_team()
        client = Client.objects.create(
                name=lead.name,
                email=lead.email,
                phone=lead.phone,
                Address=lead.Address,
                property_price=lead.property_price,
                property_size=lead.property_size,
                property_locality=lead.property_locality,
                property_type=lead.property_type,
                priority=lead.priority,
                created_by=request.user,
                team=team
            )
        lead.converted_to_client = True
        lead.save()
        messages.success(request, 'This lead was converted to client')
        return redirect('leads:list')

leads/templates/leads/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6 bg-gradient">
        <div class="glass">
    <div class="py-6 px-6  bg-gradient-to-r from-rose-500 via-red-400 to-red-500">
        <h1 class="mb-4 text-4xl" style="color:  white;">{{ lead.name }}</h1>

        {% if lead.description %}
            <p class="text-2xl font-semibold text-white">Description</p>
            <p class="mb-2 text-white">{{ lead.description }}</p>
        {% endif %}

        <p class="text-2xl font-semibold text-white">Priority</p>
        <p class="mb-2 text-white">{{ lead.get_priority_display }}</p>

        <p class="text-2xl font-semibold text-white">Status</p>
        <p class="mb-2 text-white">{{ lead.get_status_display }}</p>

        <p class="text-2xl font-semibold text-white">Created at</p>
        <p class="mb-2 text-white">{{ lead.created_at }}</p>

        <p class="text-2xl font-semibold text-white">Modifed at</p>
        <p class="mb-6 text-white">{{ lead.modified_at }}</p>
        <hr class="my-4 text-white">

        <form id="lead_delete_form" method="post" action = "{% url 'leads:delete' lead.id %}">
        {% csrf_token %}
        </form>

        <a href="{% url 'leads:convert' lead.id %}" class="text-2x1 py-3 px-6 rounded-xl bg-sky-blue-500 text-white" style="background-color: #3f84bd;">Convert to Client</a>
        <a href="{% url 'leads:edit' lead.id %}" class="py-3 px-6 rounded-xl bg-teal-500 text-white">Edit</a>
        <a href="#" onclick="document.getElementById('lead_delete_form').submit();" class="py-3 px-6 rounded-xl bg-red-500 text-white">Delete</a>


        <hr class="my-4">
        <a href="{% url 'leads:list' %}" class="text-white">Back to Leads</a>
    </div>
</div>
{% endblock %}

leads/templates/leads/lead_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
        <div class="min-h-screen flex items-center justify-center bg-gradient-to-r from-blue-900 to-teal-500 py-6 px-6">
            <div class="bg-white bg-opacity-10 rounded-xl p-8 shadow-lg max-w-md w-full text-white">
                <h1 class="text-2xl mb-6">{{ title }}</h1>


            <form method="post" action=".">
                {% csrf_token %}

                {% for field in form %}
                    <div class="mb-4">
                        <label for="{{ field.id_for_label }}" class="block text-sm font-medium mb-2">{{ field.label }}</label>

                        {% if field.name == 'priority' or field.name == 'property_type' %}
                            <div class="relative">
                                <select name="{{ field.html_name }}" id="{{ field.auto_id }}" class="w-full p-2 rounded-lg border border-transparent focus:outline-none focus:border-white focus:border-opacity-20 bg-opacity-10 bg-white text-white placeholder-white placeholder-opacity-50" required>
                                    <option value="" disabled selected>Select {{ field.label }}</option>
                                    {% for choice in field.field.choices %}
                                    <option value="{{ choice.0 }}" class="text-white bg-gray-400">{{ choice.1 }}</option>
                                    {% endfor %}
                                </select>
                                <div class="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                                    
                                </div>
                            </div>
                        {% else %}
                            <input type="text" name="{{ field.html_name }}" id="{{ field.auto_id }}" class="w-full p-2 rounded-lg border border-transparent focus:outline-none focus:border-white focus:border-opacity-20 bg-opacity-10 bg-white placeholder-white placeholder-opacity-50" value="{{ field.value|default:'' }}" required/>
                        {% endif %}
                    </div>
                {% endfor %}

                <br>
                <div style="display: flex; justify-content: center; align-items: center; height: 32pt;">
                    <button class="py-3 px-8 bg-indigo-950 text-white 
                    rounded-xl hover:bg-blue-900 hover:font-bold">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

leads/templates/leads/lead_list.html
{% extends 'core/base.html' %}
{% block title %}Leads{% endblock %}
{% block content %}

    <div class="py-6 px-6 bg-gradient-to-r from-blue-900 to-teal-500">
    <h1 class="text-4xl text-white" style="padding-left: 8px; padding-bottom: 12px;">Leads</h1>
    <a href="{% url 'leads:add' %}" class="inline-block py-3 px-6 mx-auto shadow-lg
        bg-light-gray-400 text-white
        rounded-2xl hover:font-bold  hover:text-black" 
        style="background-color: rgb(231 231 231 / 22%);backdrop-filter: blur(10px);">
        Add Lead
    </a>
        {% if object_list %}
        <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Email</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
            </div>
            {% for lead in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'leads:detail' lead.id %}">{{ lead.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.email }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
                </div>
                {% endfor %}
    {% else %}
            <p class="mt-6 px-2 text-white">There are no entries yet...</p>
    {% endif %}
</div>
{% endblock %}