ConnectX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
from core.views import index,about
from userprofile.forms import LoginForm
urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('leads.urls')),
    path('dashboard/clients/', include('clients.urls')),
    path('dashboard/teams/', include('teams.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('search/', include('core.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name ='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from .import views

app_name = 'clients'

urlpatterns = [
    path('', views.client_list, name='list'),
    path('<int:pk>/', views.client_details, name='details'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/delete/', views.client_delete, name='delete'),
    path('add-client/', views.add_client, name='add'),
    path('export/', views.clients_export, name='export')
]

core/urls.py
from django.urls import path
from .import views
app_name = 'search'
urlpatterns=[
path('', views.search, name='search'),]

clients/models.py
from django.contrib.auth.models import User
from django.db import models
from teams.models import Team
LOW = 'low'
MEDIUM = 'medium'
HIGH = 'high'

CHOICES_PRIORITY = (
    (LOW, 'Low'),
    (MEDIUM, 'Medium'),
    (HIGH, 'High'),
)

plot = 'plot'
readyTomove = 'readyToMove'
apartment = 'apartment'

Property_type = (
    (plot, 'plot'),
    (readyTomove, 'readyTomove'),
    (apartment, 'apartment'),
)
class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=11, default=' ')
    Address = models.TextField(max_length=50, default=' ',blank=False,null=False)
    property_price = models.IntegerField(default='00')
    property_size = models.CharField(max_length=25,default=' ')
    property_locality = models.CharField(max_length=25, default=' ')
    property_type = models.CharField(max_length=11, choices=Property_type, default=plot)
    converted_to_client = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

clients/forms.py
from django import forms
from .models import Client


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'phone', 'Address')

clients/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
import csv
from django.http import HttpResponse
from teams.models import Team
from .models import Client
from .forms import AddClientForm

@login_required
def clients_export(request):
    team = request.user.userprofile.active_team
    clients = Client.objects.filter(created_by=request.user)
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="clients.csv"'},
    )
    writer = csv.writer(response)
    writer.writerow(['Client', 'Phone', 'Email', 'Address', 'Created At', 'Created By'])
    for client in clients:
        writer.writerow([client.name, client.phone, client.email, client.Address, client.created_at, client.created_by])
    return response


@login_required
def client_list(request):
    team = request.user.userprofile.active_team
    clients = Client.objects.filter(created_by=request.user)
    return render(request,'clients/clients_list.html', {'clients': clients})


@login_required
def client_delete(request, pk):
    team = request.user.userprofile.active_team
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()
    messages.success(request, 'This Client was deleted')
    return redirect('clients:list')


@login_required
def clients_edit(request, pk):
    team = request.user.userprofile.active_team
    clients = get_object_or_404(Client, created_by=request.user, pk=pk)
    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=clients)
        if form.is_valid():
            form.save()
            messages.success(request, 'This changes were saved')
            return redirect('clients:list')
    else:
        form = AddClientForm(instance=clients)
    return render(request, 'clients/clients_edit.html', {'form': form})


@login_required
def client_details(request, pk):
    team = request.user.userprofile.active_team
    client=get_object_or_404(Client, created_by=request.user,pk=pk)
    return render(request, 'clients/clients_details.html', {'client': client})

@login_required
def client_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    return redirect('clients:details', pk=pk)

@login_required
def add_client(request):
    if request.method == 'POST':
        form = AddClientForm(request.POST)
        if form.is_valid():
            team=Team.objects.filter(created_by=request.user)[0]
            client = form.save(commit=False)
            client.created_by = request.user
            client.team=request.user.userprofile.get_active_team()
            client.save()
            messages.success(request, 'This client was created')
            return redirect('dashboard:dashboard')
    else:
        form = AddClientForm()
    return render(request, 'clients/clients_add.html', {'form':form})

clients/templates/clients/clients_add.html
{% extends 'core/base.html' %}
{% block title %}Add Client{% endblock %}
{% block content %}
    <div class="min-h-screen flex items-center justify-center bg-gradient-to-r from-blue-900 to-teal-500 py-6 px-6">
    <div class="bg-white bg-opacity-10 rounded-xl p-8 shadow-lg max-w-md w-full text-white">

    <h1 class="text-2xl mb-6">Add Client</h1>


    <form method="post" action=".">
                {% csrf_token %}

                {% for field in form %}
                    <div class="mb-4">
                        <label for="{{ field.id_for_label }}" class="block text-sm font-medium mb-2">{{ field.label }}</label>
                        <input type="text" name="{{ field.html_name }}" id="{{ field.auto_id }}" class="w-full p-2 rounded-lg border border-transparent focus:outline-none focus:border-white focus:border-opacity-20 bg-opacity-10 bg-white placeholder-white placeholder-opacity-50" value="{{ field.value|default:'' }}" required/>
                    </div>
                {% endfor %}
                <br>
                <div style="display: flex; justify-content: center; align-items: center; height: 32pt;">
                    <button class="py-3 px-8 bg-indigo-950 text-white 
                    rounded-xl hover:bg-blue-900 hover:font-bold">Submit</button>
                </div>

            </form>
    </div>
    </div>
{% endblock %}

clients/templates/clients/clients_details.html
{% extends 'core/base.html' %}
{% block title %}{{ client.name }}{% endblock %}
{% block content %}
    <div class="py-6 px-6 bg-gradient">
        <div class="glass">
    <div class="py-6 px-6  bg-gradient-to-r blue-gradient">

        <h1 class="mb-4 text-4xl" style="color:  white;">{{ client.name }}</h1>
        {% if client.description %}
            <p class="font-semibold">Description</p>
            <p class="mb-2">{{ client.description }}</p>
        {% endif %}

        <p class="text-2xl font-semibold text-white">Created at</p>
        <p class="mb-2 text-white">{{ client.created_at }}</p>

        <p class="text-2xl font-semibold text-white">Modifed at</p>
        <p class="mb-6 text-white">{{ client.modified_at }}</p>
        <hr class="my-4 text-white">


        <a href="{% url 'clients:edit' client.id %}" class="py-3 px-6 rounded-xl bg-teal-500 text-white">Edit</a>
        <a href="{% url 'clients:delete' client.id %}" class="py-3 px-6 rounded-xl bg-red-500 text-white">Delete</a>

        <hr class="my-4">
        <a href="{% url 'clients:list' %}" class="text-white">Back to clients</a>
    </div>
        </div></div>
{% endblock %}

clients/templates/clients/clients_edit.html
{% extends 'core/base.html' %}
{% block title %}Edit Client{% endblock %}
{% block content %}
    <<div class="min-h-screen flex items-center justify-center bg-gradient-to-r from-blue-900 to-teal-500 py-6 px-6">
    <div class="bg-white bg-opacity-10 rounded-xl p-8 shadow-lg max-w-md w-full text-white">

    <h1 class="text-2xl mb-6">Edit Client</h1>

    <form method="post" action=".">
                {% csrf_token %}

                {% for field in form %}
                    <div class="mb-4">
                        <label for="{{ field.id_for_label }}" class="block text-sm font-medium mb-2">{{ field.label }}</label>
                        <input type="text" name="{{ field.html_name }}" id="{{ field.auto_id }}" class="w-full p-2 rounded-lg border border-transparent focus:outline-none focus:border-white focus:border-opacity-20 bg-opacity-10 bg-white placeholder-white placeholder-opacity-50" value="{{ field.value|default:'' }}" required/>
                    </div>
                {% endfor %}

                <div style="display: flex; justify-content: center; align-items: center; height: 32pt;">
                    <button class="py-3 px-6 bg-indigo-950 text-white  
                    rounded-xl hover:font-bold
                    transition duration-200 hover:text-white
                    ">Submit</button>
                </div>

            </form>
    </div></div>
{% endblock %}

clients/templates/clients/clients_list.html
{% extends 'core/base.html' %}
{% block title %}Clients{% endblock %}
{% block content %}
    <div class="py-6 px-6 bg-gradient-to-r from-blue-900 to-teal-500">
    <h1 class="text-4xl text-white" style="padding-left: 8px; padding-bottom: 12px;">Clients</h1>
        <a href="{% url 'clients:add' %}" class="inline-block py-3 px-6 mx-auto shadow-lg
        bg-light-gray-400 text-white
        rounded-2xl hover:font-bold  hover:text-black
        transition-all ease-linear" 
        style="background-color: rgb(231 231 231 / 22%);backdrop-filter: blur(10px);">Add Client</a>

       <a href="{% url 'clients:export' %}" class="inline-block py-3 px-6 mx-auto shadow-lg
        bg-light-gray-400 text-white
        rounded-2xl hover:font-bold  hover:text-black" 
        style="background-color: rgb(231 231 231 / 22%);
        backdrop-filter: blur(10px);">Export Client</a>

       <div class="mt-6 flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Email</p>
    </div>

            {% for client in clients %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'clients:details' client.id %}">{{ client.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ client.email }}</p>
                </div>
            {% endfor %}

</div>
{% endblock %}