ConnectX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
from core.views import index,about
from userprofile.forms import LoginForm
urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('leads.urls')),
    path('dashboard/clients/', include('clients.urls')),
    path('dashboard/teams/', include('teams.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('search/', include('core.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name ='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from .import views

app_name = 'clients'

urlpatterns = [
    path('', views.client_list, name='list'),
    path('<int:pk>/', views.client_details, name='details'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/delete/', views.client_delete, name='delete'),
    path('add-client/', views.add_client, name='add'),
    path('export/', views.clients_export, name='export')
]

core/urls.py
from django.urls import path
from .import views
app_name = 'search'
urlpatterns=[
path('', views.search, name='search'),]

dashboard/urls.py
from django.urls import path
from . import views
app_name='dashboard'
urlpatterns = [
    path('',views.dashboard, name='dashboard')
]

leads/urls.py
from django.urls import path
from .import views
app_name='leads'
urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('add-lead/', views.LeadCreateView.as_view(), name='add'),
]

dashboard/models.py
from django.db import models

# Create your models here.

leads/models.py
from django.contrib.auth.models import User
from django.db import models
from teams.models import Team


class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )
    plot = 'plot'
    readyTomove = 'readyTomove'
    apartment = 'apartment'

    Property_type=(
        (plot, 'plot'),
        (readyTomove, 'readyTomove'),
        (apartment, 'apartment'),
    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=11,default=' ')
    Address = models.TextField(max_length=50, default=' ',blank=False,null=False)
    property_price = models.IntegerField(default='00')
    property_size = models.CharField(max_length=25,default=' ')
    property_locality = models.CharField(max_length=25, default=' ')
    property_type = models.CharField(max_length=11, choices=Property_type, default=plot)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from leads.models import Lead
from clients.models import Client
from teams.models import Team
@login_required
def dashboard(request):
    team = request.user.userprofile.get_active_team()
    leads = Lead.objects.filter(team=team,created_by=request.user).order_by('-created_at')[0:5]
    clients = Client.objects.filter(team=team,created_by=request.user).order_by('-created_at')[0:5]
    lead_count = Lead.objects.filter(converted_to_client=False,created_by=request.user,team=team).count()
    client_count = Client.objects.filter(team=team, created_by=request.user).count()
    leadtoclient_count = Lead.objects.filter(converted_to_client=True,created_by=request.user,team=team).count()
    plot = Lead.objects.filter(property_type='plot',converted_to_client=False,created_by=request.user,team=team).count()
    apartment = Lead.objects.filter(property_type='apartment',converted_to_client=False,created_by=request.user,team=team).count()
    readytomove = Lead.objects.filter(property_type='readyTomove',converted_to_client=False,created_by=request.user,team=team).count()
    property_type_label = ['Plot' ,'Apartment', 'ReadyToMove']
    property_type = [plot,apartment,readytomove]
    low = Lead.objects.filter(priority='low',converted_to_client=False,created_by=request.user,team=team).count()
    high = Lead.objects.filter(priority='high',converted_to_client=False,created_by=request.user,team=team).count()
    medium = Lead.objects.filter(priority='medium',converted_to_client=False,created_by=request.user,team=team).count()
    priority_label = ['Low', 'High', 'Medium']
    priority = [low, high, medium]
    data=[]
    if request.GET.get('readyTomove'):
        print('user clicked summary')
        data = Lead.objects.filter(property_type='readyTomove',converted_to_client=False,team=team)

    data1 = []
    if request.GET.get('plot'):
        print('user clicked summary')
        data1 = Lead.objects.filter(property_type='plot', converted_to_client=False, team=team)

    data2 = []
    if request.GET.get('apartment'):
        print('user clicked summary')
        data2 = Lead.objects.filter(property_type='apartment', converted_to_client=False, team=team)

    return render(request,'dashboard/dashboard.html', {'leads':leads, 'clients':clients, 'lead_count':lead_count,
                                                       'client_count':client_count,'leadtoclient_count':leadtoclient_count,
                                                       'property_type_label':property_type_label, 'property_type':property_type,
                                                       'priority_label':priority_label, 'priority':priority,"data":data,
                                                       "data1":data1,"data2":data2})

dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}

{% block content %}
<style>
   .div2, .div3, .div4{background: rgba( 255, 255, 255, 0.2 );
box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
backdrop-filter: blur( 11px );
-webkit-backdrop-filter: blur( 11px );
border-radius: 10px;
border: 1px solid rgba( 255, 255, 255, 0.18 );
  }
  .div2, .div3, .div4{
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
  }
  .leadsquare, .clientsquare, .leadtoclientsquare {
    padding-top: 25px;
    text-align: center;
    font-weight: bolder;
    width:400px;
    height: 80px;
    margin-left: 10px;
    border-radius: 10px;
    margin-top: 10px;
  }

 </style>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<div class="py-6 px-6 ">

    <div class="mb-6 text-4xl text-gray-100 font-serif " >Dashboard</div>
    <div class="div1" style="width:1250px; height:100px;display: flex;margin-left: -12px;">

<hr>
   <form action="" method="get">

  <label for="cars">Choose a car:</label>
        <select>
  <option type="submit" value="plot" name="plot">plot</option>
  <option type="submit" value="apatment" name="apartment">apartment</option>
  <option type="submit" value="readyTomove" name="readyTomove">readyTomove</option>
       </select>
</form>s
<hr>
{% for result in data %}
                <tr>
                    <td>{{result.name}}</td>
                </tr>
{% endfor %}
    {% for result in data1 %}
                <tr>
                    <td>{{result.name}}</td>
                </tr>
{% endfor %}
    {% for result in data2 %}
                <tr>
                    <td>{{result.name}}</td>
                </tr>
{% endfor %}

      <div class="leadsquare text-xl hover:bg-slate-950 text-white" style="background: #f12711;
background: -webkit-linear-gradient(to right, #f5af19, #f12711);
background: linear-gradient(to right, #f5af19, #f12711);padding-left: 5px;text-align: left
">Leads : {{ lead_count }} <img src="{% static 'images/lead.png' %}" style="width: 80px;height: 80px;float: right;margin-top: -25px;"></div><br>
      <div class="clientsquare text-xl hover:bg-slate-950 text-white" style="background: #00F260;
background: -webkit-linear-gradient(to right, #0575E6, #00F260);
background: linear-gradient(to right, #0575E6, #00F260);text-align: left; margin-left:25px;padding-left: 5px;
">Clients : {{ client_count }} <img src="{% static 'images/client.png' %}" style="width: 70px;height: 65px;float: right;margin-top: -15px;padding-right: 10px;"></div></div><br>
      <div class="leadtoclientsquare text-xl hover:bg-slate-950 text-white" style="background: #bc4e9c;
background: -webkit-linear-gradient(to right, #f80759, #bc4e9c);margin-left: 65%;margin-top: -113px;
background: linear-gradient(to right, #f80759, #bc4e9c); text-align: left;padding-left: 5px;">Leads converted to client : {{ leadtoclient_count }}
      <img src="{% static 'images/leadclient.png' %}" style="width: 95px;height: 85px;float: right;margin-top: -30px;padding-right: 10px"></div>
    </div>

  <div class="div2 mt-10 px-8 py-10" style="width:400px; height:400px;display: inline-block;margin-left: 20px;">
      <canvas id="chart1" style="padding-left: 10px;margin-top: 60px;height:300px" ></canvas>
  </div>
<script>
const ctx = document.getElementById('chart1');
  var chart1 = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Lead vs Client'],
      datasets: [{
        label: 'Leads',
        data: [{{ lead_count }}],
        backgroundColor:['rgb(226,76,197)'],
      }
      ,{
        label: 'Clients',
        data: [{{ client_count }}],
        backgroundColor:['rgb(24,176,188)'],
      }],
    },
    options: {
           color:['white'],
        responsive: true,
      scales: {
        y: {
            ticks: { color: 'white', beginAtZero: true },
          beginAtZero: true,
            grid: {
          color: 'white'
        }
        },
          x: {
        ticks: { color: 'white', beginAtZero: true },

      }
      }
    }
  });
</script>

  <div class="div3 mt-10 py-10" style="width:400px; height:400px;display: inline-block;margin-left: 20px;">
    <canvas id="chart2" style="margin-left: 40px;"></canvas>
  </div>

  <script>
    var ctx1 = document.getElementById('chart2');
    var chart2 = new Chart(ctx1, {
        type: 'doughnut',
         data: {
                labels: [{% for topic in property_type_label %} '{{ topic }}', {% endfor %}],
                datasets: [{
                    label:'Frequency',
                    data: [{% for number in property_type %} '{{ number }}', {% endfor %}],
                    backgroundColor:['rgb(224,162,17)','rgb(226,76,197)', 'rgb(24,176,188)'],
                    borderWidth:1,
                }]
            },
        options: {

            color:['white'],
            responsive:true,

        }
      });
    </script>

  <div class="div4 px-8 py-10" style="width:400px; height:400px;display: inline-block;margin-left: 20px;">
    <canvas id="chart3" ></canvas>
  </div>

<script>
var ctx2 = document.getElementById('chart3');
var chart3 = new Chart(ctx2, {
    type: 'polarArea',
     data: {
            labels: [{% for one in priority_label %} '{{ one }}', {% endfor %}],
            datasets: [{
                label:'Frequency',
                data: [{% for two in priority %} '{{ two }}', {% endfor %}],
               backgroundColor:['rgba(224,162,17,0.82)','rgba(226,76,197,0.82)', 'rgba(24,176,188,0.82)'],

            }]
        },
    options: {
        color:['white'],
        responsive:true
    }
  });
</script>

<br>
    <div class="flex space-x-4 my-8" >
        <div class="px-4 py-6 bg-gray-100 rounded-xl leads" style="margin-left: 20px;width:610px;
          background: rgba( 255, 255, 255, 0.2 );
          box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
          backdrop-filter: blur( 11px );
          -webkit-backdrop-filter: blur( 11px );
          border-radius: 10px;
          border: 1px solid rgba( 255, 255, 255, 0.18 );">
        <h2 class="mb-4 text-lg">Newest leads</h2>

            {% for lead in leads %}
                <div class="mb-2 lead" >
                    <h3 class="font-semibold">{{ lead.name }}</h3>

                    <p class="text-xs">Status: {{ lead.get_status_display }}</p>
                    <p class="text-xs">Priority: {{ lead.get_priority_display }}</p>

                    <a href="{% url 'leads:detail' lead.pk %}">Details</a>
                </div>
            {% endfor %}
        </div>

        <div class=" px-4 py-6 bg-gray-100 rounded-xl clients" style="margin-left: 33px;width:610px;
        background: rgba( 255, 255, 255, 0.2 );
        box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
        backdrop-filter: blur( 11px );
        -webkit-backdrop-filter: blur( 11px );
        border-radius: 10px;
        border: 1px solid rgba( 255, 255, 255, 0.18 );">
            <h2 class="mb-4 text-lg">Newest clients</h2>

            {% for client in clients %}
                <div class="mb-2 client">
                    <h3 class="font-semibold">{{ client.name }}</h3>

                    <a href="{% url 'clients:details' client.pk %}">Details</a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}