ConnectX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
from core.views import index,about
from userprofile.forms import LoginForm
urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('leads.urls')),
    path('dashboard/clients/', include('clients.urls')),
    path('dashboard/teams/', include('teams.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('search/', include('core.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name ='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/urls.py
from django.urls import path
from .import views

app_name = 'clients'

urlpatterns = [
    path('', views.client_list, name='list'),
    path('<int:pk>/', views.client_details, name='details'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/delete/', views.client_delete, name='delete'),
    path('add-client/', views.add_client, name='add'),
    path('export/', views.clients_export, name='export')
]

core/urls.py
from django.urls import path
from .import views
app_name = 'search'
urlpatterns=[
path('', views.search, name='search'),]

dashboard/urls.py
from django.urls import path
from . import views
app_name='dashboard'
urlpatterns = [
    path('',views.dashboard, name='dashboard')
]

leads/urls.py
from django.urls import path
from .import views
app_name='leads'
urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('add-lead/', views.LeadCreateView.as_view(), name='add'),
]

userprofile/urls.py
from django.urls import path
from .import views
app_name='userprofile'


urlpatterns=[
    path('myaccount', views.myaccount , name='myaccount'),
    path('sign-up/', views.signup, name='signup'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from clients.models import Client
from leads.models import Lead
def index(request):

    return render(request, 'core/index.html')

def search(request):
    query = request.GET.get('q', '')
    lead_object_list = Lead.objects.filter(name__icontains=query, converted_to_client=False,created_by=request.user)
    client_object_list = Client.objects.filter(name__icontains=query)
    return render(request, 'core/search.html',{'lead_object_list': lead_object_list, 'client_object_list': client_object_list})
def about(request):
    return render(request, 'core/about.html')

core/templates/core/partials/footer.html
<footer class="py-8 text-center bg-gray-900">
    <p class="text-large" style="color: aliceblue;">Copyright(c) 2023 - ConnectX</p>
</footer>

core/templates/core/partials/navbar.html
{% load static %}
<nav class="py-4 px-6 flex justify-between " style="background: rgba( 8, 59, 122, 0.5 );
box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
backdrop-filter: blur( 10px );
-webkit-backdrop-filter: blur( 10px );
border-radius: 10px;
border: 1px solid rgba( 255, 255, 255, 0.18 );">
    <img src="{% static 'images/logo.png' %}" style="height:30px;width:30px;"> 
    <a href="/" class="text-white"><strong style="font-size: 19px; margin-left: -80px;"> ConnectX</strong></a>


    <form method="get" action="{% url 'search:search' %}" style="margin-top: -5px" >
        <input type="text" name="q" placeholder="Search..."
               style="border: 3px solid #13134f;width: 250px;height: 35px;border-radius: 5px"/>
        <button class="hover:font-bold" type="submit" style="border: 2px solid #13134f;height: 37px;border-radius: 7px;color:white;padding:2px;margin-left: 5px;background-color: #13134f;width: 100px">Search</button>
    </form>


      <div class="space-x-2 mt-1">
          {% if request.user.is_authenticated %}
          <a href="{% url 'dashboard:dashboard' %}" class="py-2 px-6 text-white hover:bg-blue-200 hover:text-black hover:rounded-xl">Dashboard</a>
          <a href="{% url 'leads:list' %}" class="py-2 px-6 text-white hover:bg-blue-200 hover:text-black hover:rounded-xl">Leads List</a>
          <a href="{% url 'clients:list' %}" class="py-2 px-6 text-white hover:bg-blue-200 hover:text-black hover:rounded-xl">Clients List</a>
          <a href="{% url 'userprofile:myaccount' %}" class=" py-2 px-6 text-white hover:bg-blue-200 hover:text-black hover:rounded-xl">MyAccount</a>
          {% else %}
          <a href="{% url 'login' %}" class="py-2 px-6 text-white hover:bg-blue-200 hover:text-black hover:rounded-xl">Login</a>
          <a href="{% url 'userprofile:signup' %}" class="py-2 px-6 text-white hover:bg-blue-200 hover:text-black hover:rounded-xl">SignUp</a>
          {% endif %}
          <a href="{% url 'about' %}" class="py-2 px-6 text-white hover:bg-blue-200 hover:text-black hover:rounded-xl">About</a>
      </div>
  </nav>